# workflow to download, configure and run keycloak server (Java environment). Install Python dependencies
# Run integration tests - Test Auth/Authz using JWT tokens from Keycloak to access public and protected REST API endpoints

name: Auth-RESTAPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  ALICE_PWD: ${{ secrets.ALICE_PWD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up and start Keycloak Server
      run: .github/scripts/config-keycloak.sh

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install --user pipx
        pipx install poetry

    - name: Install dependencies
      run: poetry install

    - name: Get JWT access token for user
      run: .github/scripts/get-user-token.sh

    - name: Test with pytest
      run: poetry run pytest
